### ISSUE TITLE
`oss2.defaults.connection_pool_size`如何设置一个合理值？

### ISSUE THREAD

**Issue by Lovecanon** [aliyun/aliyun-oss-python-sdk#100]
`oss2.defaults.connection_pool_size=30`，线程数和连接池数量一致，上传速度才600kb/s，但CPU占用率接近200%
我该如何设置线程数和连接池数量？有没有其他提高上传速度的方法？
注： endpoint使用的是VPC网络

**Comment by Lovecanon** [comment]
关闭`crc`校验即可
`bucket = oss2.Bucket(auth, oss_endpoint, bucket_name, enable_crc=False)`

**Comment by yami** [comment]
感觉就算crc开启了，也不应该这么慢，感觉哪里有瓶颈。
