### ISSUE TITLE
oss2 怎样上传一个文件夹

### ISSUE THREAD

**Issue by dinglioutlook** [aliyun/aliyun-oss-python-sdk#102]
你好，

请问怎样在oss2里面上传整个文件夹？我发现OSS Browser可以做到，但是oss2我尝试了bucket.put_object_from_file(), 如果指定文件夹会抛异常。在oss2 bucket中没有发现其它可用的接口。请指教。

Li

**Comment by yami** [comment]
oss2是SDK，只提供最基础，最通用的功能。具体到这个问题上，OSS本质上没有目录的概念。只是控制台展示为了对用户的友好性，采用了以 "/" 为目录的展现。

如果你需要实现这样的功能，就需要自己遍历目录，然后把文件按照一定的组织方式上传到OSS上。

要做好的话，这里需要注意的问题其实还蛮多。比如说如何实现断点续传？是不是要实现增量上传？"." ".."怎么处理? windows目录的字符集需要处理为UTF8等等。

**Comment by KeithTt** [comment]
> oss2是SDK，只提供最基础，最通用的功能。具体到这个问题上，OSS本质上没有目录的概念。只是控制台展示为了对用户的友好性，采用了以 "/" 为目录的展现。
> 
> 如果你需要实现这样的功能，就需要自己遍历目录，然后把文件按照一定的组织方式上传到OSS上。
> 
> 要做好的话，这里需要注意的问题其实还蛮多。比如说如何实现断点续传？是不是要实现增量上传？"." ".."怎么处理? windows目录的字符集需要处理为UTF8等等。

问题确实还蛮多的，但是竟然不支持就很奇怪，而且也没有 example...
