### ISSUE TITLE
max_keys参数无效

### ISSUE THREAD

**Issue by yinbiao** [aliyun/aliyun-oss-python-sdk#104]
通过测试发现list_objects 这个函数是支持分页的，但oss2.ObjectIterator函数的max_keys是无效的。

**Comment by yinbiao** [comment]
通过测试发现list_objects 这个函数是支持分页的，但oss2.ObjectIterator函数的max_keys是无效的。

**Comment by yami** [comment]
具体你参考一下oss2.ObjectIterator的帮助文档。这个iterator会列出所有的文件，max_keys是内部的实现，表示每次调用list_objects要返回多少个key。

如果你不想用ObjectIterator，而是要自己限制max_keys，那么就用list_objects接口。

总结一下，这个是by design的。
