### ISSUE TITLE
oss2 AuthV2 pypi没有上传最新的包

### ISSUE THREAD

**Issue by istommao** [aliyun/aliyun-oss-python-sdk#105]
oss2 AuthV2 pypi没有上传最新的包

**Comment by 0xMingYang** [comment]
能具体描述一下问题吗？

**Comment by istommao** [comment]
就是 pypi上 你们 没传最新的包

**Comment by 0xMingYang** [comment]
pypi上都是正式release的版本，authV2的代码还没有正式进入release，所以这个是符合预期的。我们会尽快把V2签名进到release里面。

**Comment by istommao** [comment]
我已经在正式环境 用 V2了😄

**Comment by 0xMingYang** [comment]
@istommao 另外也请不要使用oss2 master代码进行开发，而是基于我们官方发布的release。
