### ISSUE TITLE
请问如何上传图片？

### ISSUE THREAD

**Issue by x11wu** [aliyun/aliyun-oss-python-sdk#118]
examples/image.py 
key = 'example.jpg'
new_pic = 'new-example.jpg'

# 上传示例图片
bucket.put_object_from_file(key, 'example.jpg')

# 获取图片信息
result = bucket.get_object(key, process='image/info')

**Comment by rhinoceros** [comment]
https://www.alibabacloud.com/help/zh/doc-detail/32030.htm?spm=a2c63.p38356.b99.167.158b4c193FGIIk#%E7%AE%80%E5%8D%95%E4%B8%8A%E4%BC%A0
