### ISSUE TITLE
batch delete objects too large

### ISSUE THREAD

**Issue by Explorer1092** [aliyun/aliyun-oss-python-sdk#119]
调用 batch_delete_objects 有如下错误

oss2.exceptions.MalformedXml: {'status': 400, 'request-id': '5B52C830DD373E570F081EBE', 'details': {'HostId': 'xxxxx.oss-cn-hangzhou.aliyuncs.com', 'Message': 'The XML you provided was not well-formed or did not validate against our published schema.', 'Code': 'MalformedXML', 'RequestId': '5B52C830DD373E570F081EBE', 'ErrorDetail': 'batch delete objects too large'}}

**Comment by hangzws** [comment]
参考 https://help.aliyun.com/document_detail/31983.html?spm=a2c4g.11186623.6.1003.5efd73581l5fEY，批量删除最多支持删除1000个objects，如果还是有改问题，请联系我们。
