### ISSUE TITLE
bucket.sign_rtmp_url

### ISSUE THREAD

**Issue by cjk7713** [aliyun/aliyun-oss-python-sdk#132]
想实现推rtmp流生成的playlistname为时间戳，需要怎么实现？

**Comment by cjk7713** [comment]
项目想实现摄像头推rtmp流到oss存储hls，或者有其他方案做？类似海康萤石那类的云存储

**Comment by cjk7713** [comment]
难道说不行？36+

**Comment by hangzws** [comment]
playlistname可以通过代码自己生成，推流支持传入playlistname作为参数。具体请参考：https://help.aliyun.com/document_detail/44303.html?spm=a2c4g.11186623.6.1061.106571f6nFydw7
