### ISSUE TITLE
需要在没有外网但可以使用代理的服务器上，上传文件到oss，该如何设置代理

### ISSUE THREAD

**Issue by duanzhanling** [aliyun/aliyun-oss-python-sdk#136]
需要在没有外网但可以使用代理的服务器上，上传文件到oss，该如何设置代理

**Comment by mikegreen7892003** [comment]
oss 用的是 requests

http://docs.python-requests.org/zh_CN/latest/user/advanced.html#proxies

设置环境变量的方法应该有效。

**Comment by duanzhanling** [comment]
好，我去测试下，暂时先关闭。谢谢
