### ISSUE TITLE
断点续传下载resumable_download 自定义log目录 store 报错

### ISSUE THREAD

**Issue by jayfmQQ** [aliyun/aliyun-oss-python-sdk#138]
代码：
oss2.resumable_download(self.bucket, key, self.tempFile , store=self.logFile , num_threads=4,progress_callback=self.percentage)

报错信息：
'str' object has no attribute 'make_store_key'

无论我设置 self.logFile 是个文件还是目录都报这个错误

只有去除掉store=self.logFile这个参数才是正常的

**Comment by liyanzhang505** [comment]
You can use oss2.ResumableDownloadStore  to make store option, please refer to https://help.aliyun.com/document_detail/88444.html?spm=5176.11065259.1996646101.searchclickresult.18569d8eCLwRan
