### ISSUE TITLE
python sdk本地文件上传失败

### ISSUE THREAD

**Issue by amennihao** [aliyun/aliyun-oss-python-sdk#139]
headers = utils.set_content_type(http.CaseInsensitiveDict(headers), key)
TypeError: 'NoneType' object is not iterable

原因是：headers初始化为none，在调用put_object()时，headers执行指定为{}即可

**Comment by king41409** [comment]
bucket.put_object('hello.txt', 'hello world', None, None) 可以上传文件，没有出现问题。

**Comment by coderall** [comment]
检查下调用接口的参数是否正确设置，如果有其他错误，把requestid 发出来
