### ISSUE TITLE
oss://和http://区别

### ISSUE THREAD

**Issue by hackenzheng** [aliyun/aliyun-oss-python-sdk#148]
对象存储oss的使用中，每个文件有一个对应的url，可以在浏览器中输入直接下载， 在阿里的pai平台中可以通过oss://开头的路径也能直接读取， 这两种方式有什么区别？ 好奇为什么oss://开头就能直接读取？

**Comment by hangzws** [comment]
这个只是个规则而已，没有特别的含义。
