### ISSUE TITLE
获取一个对象时打印的日志太多了， 应该设置成debug

### ISSUE THREAD

**Issue by cuihaikuo** [aliyun/aliyun-oss-python-sdk#151]

**Comment by cuihaikuo** [comment]
[2018-12-17 11:37:15,064] [INFO] Get object done, req_id: 5C1719EA2BFA71834F6E0D61, status_code: 200
[2018-12-17 11:37:15,065] [INFO] Start to get object, bucket: dev-commits， key: 12a93d3c-60fc-/8d5a0cd9e, range: , headers: {}, params: {}

每获取一个对象就打印一堆

**Comment by messense** [comment]
+1

**Comment by hangzws** [comment]
用户可以参考[https://help.aliyun.com/document_detail/97728.html?spm=a2c4g.11186623.6.731.5efd735844rfkV](https://help.aliyun.com/document_detail/97728.html?spm=a2c4g.11186623.6.731.5efd735844rfkV)设置默认的日志级别，下一个版本（2.6.1），我们将取消设置默认日志级别

**Comment by messense** [comment]
其实直接把现在的 logger.info 改成 logger.debug 就挺好，现在大部分的 info 级别打出来的 log 都在生产环境没什么用反而污染日志。

**Comment by messense** [comment]
FYI: https://docs.python-guide.org/writing/logging/#logging-in-a-library

**Comment by hangzws** [comment]
info级别是大于debug级别的，改成debug不是打印的更多？

**Comment by messense** [comment]
正常情况 logging 默认级别生产环境最起码是 INFO 呀

**Comment by messense** [comment]
比方说我们生产环境 logging 全局默认级别是 INFO，oss2 里面也是 INFO 才被 log 出来了，如果是 debug 就会被自动过滤掉了。

**Comment by cuihaikuo** [comment]
就是说， 如果不想要这些INFO， 只能设成WARNING， 但这样又会漏掉一些INFO

**Comment by hangzws** [comment]
这本身没有什么问题啊，就是这么设计的
