### ISSUE TITLE
pipenv install oss2 报错

### ISSUE THREAD

**Issue by xinming90** [aliyun/aliyun-oss-python-sdk#153]
os: mac 10.14.2
python: 3.7.1

错误信息:
    raise TypeError('Expected a pinned InstallRequirement, got {}'.format(ireq))
TypeError: Expected a pinned InstallRequirement, got aliyun-python-sdk-core from https://files.pythonhosted.org/packages/29/8f/e8c7f5a637ef4bd6612085ae1d784841b35cc6a634a72b6fb7a68a5184e3/aliyun-python-sdk-core-v3-2.11.4.tar.gz#sha256=53b427f8267bb85623354c8af0c5502d8f6b0e3caa61ef1450be498ef17a3c00

**Comment by bamboo0915** [comment]
遇到同样的错误，有成功解决的吗

**Comment by lucianl** [comment]
> 遇到同样的错误，有成功解决的吗

暂时解决办法为指定安装版本 ==2.11.0

**Comment by hangzws** [comment]
应该是依赖库aliyun-python-sdk-core 发布的版本有问题，可以尝试低版本，使用 @lucianl 提供的方式是可行的

**Comment by hangzws** [comment]
最新发版本的aliyun-python-sdk-core应该解决了这个问题，请尝试下载最新版本
