### ISSUE TITLE
delete_object status_code: 204

### ISSUE THREAD

**Issue by qingchn** [aliyun/aliyun-oss-python-sdk#156]
Python 2.7.12
oss2.__version__
'2.6.0'

在使用delete_object 如果删除的object中以/ 开头的资源如： /cover/DpmDRybVsAEQkbG.jpg
会有status_code: 204 返回，但是对应的资源不会被删除。
如果移除了/ 比如。cover/DpmDRybVsAEQkbG.jpg，
同样 还是 status_code: 204  返回，对应的资源会被删除。

以上可以在阿里云 新加坡区域重现，请问以上提示 能否区别一下。
比如带了/,无法删除时，提示非 204。

**Comment by coderall** [comment]
@qingchn delete_object 接口中的key不能以 / 或 \ 开头

**Comment by hangzws** [comment]
命名规范参考：
https://help.aliyun.com/knowledge_detail/39668.html?spm=5176.11065259.1996646101.searchclickresult.5b446be68lFzrA
这个地方确实是有问题。

**Comment by qingchn** [comment]
@coderall @hangzws  命名规范我懂，我的意思 能不能区别一下 reponse status_code 204。

**Comment by hangzws** [comment]
这个问题我们要评估一下
