### ISSUE TITLE
example里的object_basic.py 有误

### ISSUE THREAD

**Issue by Arthurzhangsheng** [aliyun/aliyun-oss-python-sdk#158]
example里的object_basic.py 的37-41行

`# 获取Object的metadata  
object_meta = bucket.get_object_meta('你的对象名')  
print('last modified: ' + object_meta.last_modified)  
print('etag: ' + object_meta.etag)  
print('size: ' + object_meta.content_length)  `

会报错TypeError: must be str, not int
需要将数据类型用str()转化为str才行，此外object_meta.last_modified返回的是时间戳，也需要自行转化为时间格式才方便阅读

**Comment by king41409** [comment]
print('last modified: ' + str(object_meta.last_modified))
print('etag: ' + object_meta.etag)
print('size: ' + str(object_meta.content_length))
python是强类型语言不支持+号作为不同类型的连接符
