### ISSUE TITLE
oss文件下载触发下载弹窗

### ISSUE THREAD

**Issue by xiongxianzhu** [aliyun/aliyun-oss-python-sdk#179]
oss python sdk有没提供接口可以生成文件下载url， 浏览器直接GET请求该URL能触发下载弹窗?

目前我的替代方案暂时是：
1. 通过OSS sdk获取文件的sign_url
2. 再通过文件的签名URL(sign_url)打开网络文件流

核心代码如下：
```
import requests

r = requests.get(url, stream=True)
response = StreamingHttpResponse(r.raw)
response['Content-Type'] = 'application/octet-stream'
response['Content-Disposition'] = 'attachment;filename="{0}"'.format(
            quote(filename, 'utf-8'))
return response
```
其中， 上面的`url`就是我通过oss sdk生成的签名url
以上是我临时的方案， 而aws的对象存储s3的sdk是有实现了生成文件的签名url，浏览器直接GET请求该文件的签名url是可以直接触发下载框的， 希望OSS python SDK也能提供这样的方法， 省去了我上面额外的代码

**Comment by coderall** [comment]
收到反馈，多谢
