### ISSUE TITLE
head_object异常处理建议

### ISSUE THREAD

**Issue by xufan6** [aliyun/aliyun-oss-python-sdk#261]
head_object中404目前是抛出class:`NotFound <oss2.exceptions.NotFound>`
但是在api文档中返回的是NoSuchKey https://help.aliyun.com/document_detail/31984.html
建议修改返回的异常类至NoSuchKey，以保持一致性。

对应的get_object，在404异常类和api中都是NoSuchKey，保持了一致。

**Comment by huiguangjun** [comment]
head method 是没有body 返回的，无法像 get_object 接口 获取 具体的错误信息。 

现在是直接以  http 的错误 直接返回。
