### ISSUE TITLE
Cyptro多平台集成问题

### ISSUE THREAD

**Issue by frank-pian** [aliyun/aliyun-oss-python-sdk#281]
oss2依赖Cyptro库，但是这个包有二进制链接库，不同平台链接库不同，这对跨平台软件集成这个SDK难度加大了很多。

**Comment by rgtjf** [comment]
确实，新版macbook m1芯片arm上就没办法支持

**Comment by frank-pian** [comment]
这个好久了，我说下我的解决方案。
我在mac平台和linux平台分别下载了cyptro包，都打包到应用程序中，然后通过判断平台来加载不同版本的包
