### ISSUE TITLE
系统时间错误导致STS无法使用

### ISSUE THREAD

**Issue by zhangliganggm** [aliyun/aliyun-oss-python-sdk#30]
Windows平台下，如果系统时间不对，会导致STS临时签名失效。列出 上传 都会返回错误。

**Comment by yami** [comment]
能贴出具体的错误吗？

OSS也要求客户端时间和服务器时间相差不能超过+/-15分钟。请问，你的场景是服务器端应用，还是客户端应用？

如果是服务器端应用，建议保证服务器端时间是准确的。

如果是客户端应用，我们可以考虑（借鉴 android/iOS OSS SDK的做法），当收到 RequestTimeTooSkewed错误码时，SDK可以考虑自己用服务器返回的时间戳进行计时，类似于：
    last-oss-server-time + (new-local-time - last-local-time)

**Comment by zhangliganggm** [comment]
具体报错有空贴上来，错误 实现方法很简单，把windows时间 加快一个小时，再运行代码就会报错了。

我是客户端应用。
获取服务器的准确时间我可以实现，但是如何在py里面 传入时间参数？

**Comment by yami** [comment]
如果有需求，可以在SDK层面进行支持。

如果SDK层面不支持的话，就要用户自行传入 x-oss-date HTTP header以取代Date标准头。这样又意味着每个接口都要让用户能够设置 HTTP header。

**Comment by zhangliganggm** [comment]
Traceback (most recent call last):
  File "D:/zhongtu/ZhongTu/Query/UUQuery.py", line 20, in t
    print bucket.put_object('fj/test3.rar', 'd:\\01.rar')
  File "C:\Python27\lib\site-packages\oss2\api.py", line 321, in put_object
    resp = self.__do_object('PUT', key, data=data, headers=headers)
  File "C:\Python27\lib\site-packages\oss2\api.py", line 865, in __do_object
    return self._do(method, self.bucket_name, key, **kwargs)
  File "C:\Python27\lib\site-packages\oss2\api.py", line 148, in _do
    raise exceptions.make_exception(resp)
oss2.exceptions.ServerError: {'status': 403, 'details': {'HostId': 'downqingmo.oss-cn-hangzhou.aliyuncs.com', 'ServerTime': '2016-04-08T05:15:43.000Z', 'Code': 'RequestTimeTooSkewed', 'RequestId': '57073E7F8CDE4E9D224C9EA3', 'MaxAllowedSkewMilliseconds': '900000', 'Message': 'The difference between the request time and the current time is too large.', 'RequestTime': '2016-04-08T06:15:36.000Z'}}

**Comment by zhangliganggm** [comment]
目前解决办法有几个。
1. 先用win32api 设置下 localTime，不过需要权限。 
2. py标准time模块进行修改。oss2导入这个修改的time模块。 time.time() 获取的时间，改成联网时间。

**Comment by yami** [comment]
如果是SDK层面解决，就按上面的思路。比如上面的出错里报的是 RequestTimeTooSkewed，我可以在代码里捕获这个异常，并把这个时间记录下来，作为last-server-time，同时记录当前的本机时间，记为last-local-time下次我做请求的时候，我就设置x-oss-date头部，使之时间和下面的等价：
```
   last-server-time + (current-local-time - last-local-time)
```

**Comment by zhangliganggm** [comment]
好的。
目前先用自定义time模块覆盖了。我们这边有好多库也涉及到这个问题，要都在SDK层改的话，需要一些时间。先这么凑合用了。。有空重构 :)
