### ISSUE TITLE
我非常想知道STS生成token机制 可以用Python实现吗

### ISSUE THREAD

**Issue by erhuabushuo** [aliyun/aliyun-oss-python-sdk#31]
我非常想知道STS生成token机制 可以用Python实现吗

**Comment by yami** [comment]
可以的。你可以参考下面链接中的文档：
  https://help.aliyun.com/document_detail/26763.html
其中涉及到系统架构，以及STS应用服务器的实现。里面貌似没有python的示例，但是想法是一样的，另外你可以参考
  https://github.com/aliyun/aliyun-oss-python-sdk/blob/master/tests/test_sts.py
这里面有个获取STS的Python的例子。

希望能够对你有所帮助。
