### ISSUE TITLE
并发进行分块上传时最终合并出来的文件会出现错乱

### ISSUE THREAD

**Issue by crazylovecat** [aliyun/aliyun-oss-python-sdk#33]
并发N个线程进行大文件分块上传，最终合并出来的文件有些分块的位置错开了（文件大小是和源文件一样的）。

调试时对比了一下，bucket.upload_part 时 part_number 的顺序是对的。

但是SizedFileAdapter传入的file_obj在读的时候没有对位置进行seek，在并发上传的时候应该保证不了会按序读取。

请问一下能提供一个分块并发上传的demo看一下吗？

**Comment by crazylovecat** [comment]
我自己试了一下，在下一个分块上传的线程启动前先让 data = fileob.read(block_size)，然后bucket.upload_part时不传入SizedFileAdapter，而传入data，这样上传上去的文件就没问题

**Comment by yami** [comment]
你用的是 https://github.com/aliyun/aliyun-oss-python-sdk/blob/master/examples/upload.py 里面的例子代码？那个例子本身是单线程的。

还是说你用的是 https://github.com/aliyun/aliyun-oss-python-sdk/blob/master/oss2/resumable.py 里面的 resumable_upload() 函数进行多线程上传？最新的版本已经在 resumable_upload()里实现了多线程，通过num_threads参数指定线程数。

**Comment by yami** [comment]
Close this issue. Feel free to reopen it if it is a real issue.
