### ISSUE TITLE
Example code for deleting bucket when it's not empty? 

### ISSUE THREAD

**Issue by vicngtor** [aliyun/aliyun-oss-python-sdk#36]
bucket.delete_bucket()

Do you have any example code of how to delete a bucket when it's not empty using delete_bucket()?

**Comment by baiyubin** [comment]
you can do as fallowing:
// delete multipart
for u in oss2.MultipartUploadIterator(bucket)
	self.bucket.abort_multipart_upload(u.key, u.upload_id)

// delete objects
for obj in oss2.ObjectIterator(bucket):
    bucket.delete_object(obj.key)

**Comment by vicngtor** [comment]
Thanks!
