### ISSUE TITLE
oss能支持图片缩略吗》

### ISSUE THREAD

**Issue by tyan4g** [aliyun/aliyun-oss-python-sdk#38]
看了一下python的SDK。
请问能添加对图片的缩略功能吗？

**Comment by yami** [comment]
当前OSS的图片处理是通过这样的方式来的，比如说我要缩略到200个高度的像素，宽按照比例缩放，我可以这样做（以杭州区域为例子，bucket为ming-oss-share，原图是Koala.jpg）：
```
  http://ming-oss-share.img-cn-hangzhou.aliyuncs.com/Koala.jpg@200h
```
如果用oss2 python SDK来做的话，只要注意两点：
1. endpoint设置为图片服务的，比如说这里就是 `http::/img-cn-hangzhou.aliyuncs.com`
1. 文件名（key）参数设置为 `Koala.jgp@200h`，也就是说把图片处理也作为文件名的一部分

可以参考下面的示例代码：
```python
>>> import oss2
>>> endpoint = 'http://img-cn-hangzhou.aliyuncs.com'
>>> auth = oss2.Auth('<你的AccessKeyId>', '<你的AccessKeySecret>')
>>> b = oss2.Bucket(auth, endpoint, '<你的Bucket>')
>>> key = 'Koala.jpg'
>>> b.get_object_to_file(key + '@100h', 'mini_koala.jpg')
<oss2.models.GetObjectResult object at 0x000000000391B358>
```
需要加一个帮助页面来说明这种用法。谢谢！

这个Issue就用来跟踪这个帮助页面的实施情况。
