### ISSUE TITLE
分片上传方法不支持MD5校验

### ISSUE THREAD

**Issue by kuroismith** [aliyun/aliyun-oss-python-sdk#50]
在init_multipart_upload 或 complete_multipart_upload方法添加文件的Content-MD5，在上传结束后会被服务器拒绝

**Comment by yami** [comment]
content-md5是根据http的标准的来的，意思就是你body内容的md5值。complete分片上传的body的content-md5自然不是整个文件本身的content-md5。init没有body，也没有做校验。

如果你要自带md5，可以在init的时候带上自定义元数据，比如叫做x-oss-meta-md5，但是注意到oss本身不会帮你做校验。

文件完整性可以用三种方法来做：
  1. 用自定义元数据传入md5，用户自己去校验
  2. 每次上传分片的时候校验分片的Content-Md5，UploadPart的返回header中会带Content-Md5，表明刚刚上传的内容的Content-Md5
  3. 用OSS提供的CRC64进行校验，可以看看put_object()等api的实现等代码。

**Comment by kuroismith** [comment]
谢谢！
