### ISSUE TITLE
resumable_upload does not return any response

### ISSUE THREAD

**Issue by JokerQyou** [aliyun/aliyun-oss-python-sdk#51]
I'm using `resumable_upload` but it does not return any response. I was using callback headers so JSON response (returned by OSS requesting the callback of my application server) was expected. I think it's a reasonable feature request. What do you think?

**Comment by yami** [comment]
You are correct. We may return last-response (response from put_object or complete_multipart_upload) to user. 

We will consider this in following releases.

**Comment by baiyubin** [comment]
Hi, fixed at v2.2.3.

**Comment by JokerQyou** [comment]
Thanks! Quick response (well, compared to aliyun-python-api repo). But I don't think this is enough.

As I've mentioned earlier, if a client is using callback to get response from application server after uploading a file, either the headers must be passed to `complete_multipart_upload` API call (the `x-oss-callback*` headers), or the callback info should be contained in the request URL. (As documented [here](https://help.aliyun.com/document_detail/31989.html))

Yet I did not see `resumable_upload` supporting any of these. Currently I'm using a monkey-patched version of `resumable_upload`, but I think it might be useful to support callback officially in it. What do you think?

**Comment by ansonhorse** [comment]
2025年，依然不能在 `resumeable_upload` 使用 `x-oss-callback` 这些 headers... aliyun sucks

**Comment by ansonhorse** [comment]
https://github.com/aliyun/aliyun-oss-python-sdk/blob/eb329ec91d24e2e52646f244863232342fa05161/oss2/resumable.py#L577-L594

**Comment by JokerQyou** [comment]
> aliyun sucks

Took me two months to learn this. Luckily I migrated away from it.
