### ISSUE TITLE
可以认为Headers中的ETag就是MD5吗？

### ISSUE THREAD

**Issue by vimagick** [aliyun/aliyun-oss-python-sdk#58]
为了避免文件重复上传，在上传前，调用[get_object_meta()][1]。
虽然获取不到`Content-MD5`, 但是可以获取到`ETag`。
发现该ETag刚好与文件MD5相同，这是巧合吗？
另外ETag使用了双引号，是有什么作用吗？

```
    HTTP/1.1 200 OK
    x-oss-request-id: 559CC9BDC755F95A64485981
    Date: Wed, 29 Apr 2015 05:21:12 GMT
    ETag: "5B3C1A2E053D763E1B002CC607C5A0FE"
    Last-Modified: Fri, 24 Feb 2012 06:07:48 GMT
    Content-Length: 344606
    Connection: keep-alive
    Server: AliyunOSS
```

谢谢!

[1]: https://help.aliyun.com/document_detail/31985.html?spm=5176.doc31980.6.870.AWwaE0

**Comment by vimagick** [comment]
https://help.aliyun.com/document_detail/31955.html

> ETag 	ETag (entity tag) 在每个Object生成的时候被创建，用于标示一个Object的内容。对于Put Object请求创建的Object，ETag值是其内容的MD5值；对于其他方式创建的Object，ETag值是其内容的UUID。ETag值可以用于检查Object内容是否发生变化。
类型：字符串
默认值：无

**Comment by NullYing** [comment]
https://help.aliyun.com/knowledge_detail/39533.html

**Comment by crapthings** [comment]
@vimagick

用这个方法传了个大文件multipartUpload etag不是 md5
