### ISSUE TITLE
Need flush in get_object_to_file

### ISSUE THREAD

**Issue by Liuchang0812** [aliyun/aliyun-oss-python-sdk#59]
https://github.com/aliyun/aliyun-oss-python-sdk/blob/d08a4a170fd960e90628ae92d39eefb252043b61/oss2/api.py#L480

**Comment by baiyubin** [comment]
`with open` can flush after complelted in get_object_to_file, so donot need flush.

**Comment by yami** [comment]
I'd like to close this issue. Feel free to re-open it with more details if there's any issue.
