### ISSUE TITLE
object_exists存在的object报NoSuchKey

### ISSUE THREAD

**Issue by EVEhehe** [aliyun/aliyun-oss-python-sdk#81]
在oss存在的文件夹使用object_exists有的key存在有的key不存在,
例如:
bucket.object_exists('xxx/xxx/1/') 结果FALSE 实际存在
bucket.object_exists('xxx/xxx/11/') 结果TRUE 实际存在

**Comment by baiyubin** [comment]
你好，在OSS里文件夹是个逻辑概念，控制台展示的时候使用。在OSS的存储中并没有文件夹，OSS从根本上说是一个Key，value存储系统。object_exists是针对key的判断的，逻辑概念上的文件夹是不支持的。
