### ISSUE TITLE
fix reuse connection 会使下载大小为零的文件报错

### ISSUE THREAD

**Issue by mikegreen7892003** [aliyun/aliyun-oss-python-sdk#82]
#78 

这段代码会使下载大小为零的文件报错。

```python
import oss2

bucket = oss2.Bucket(
    oss2.Auth("xxx", "xxx"),
    "xxx",
    "xxx",
)

bucket.get_object_to_file("xx", "xx")  # 如果oss上的文件大小为零，会报requests.exceptions.StreamConsumedError
```

因为这里已经做过一次 read，所以 `_content_consumed` 被设置为True，下次调用 read 就会报错。

而下载文件，在 `get_object_to_file` 方法中，因为其`result.content_length == 0`，会再次调用 `read` 函数，导致报错。

给两个建议

- 这里的代码去掉，不进行reuse。不是很了解requests的整个机制，不确定这样改靠不靠谱。
- 还有一种做法是在 `get_object_to_file` 方法中把 `result.content_length == 0` 和 `result.content_length is None` 一样特殊处理。

**Comment by tangyouze** [comment]
手动+1

**Comment by mikegreen7892003** [comment]
@tangyouze  回滚一个小版本就能用。另外，学长好！

**Comment by yami** [comment]
谢谢提交这个issue，我会尽快fix。
