### ISSUE TITLE
bucket.complete_multipart_upload()自定义报头MD5总是返回校验错误

### ISSUE THREAD

**Issue by Linyee** [aliyun/aliyun-oss-python-sdk#88]
def calculate_file_md5(file_name, block_size=64 * 1024):
        """计算文件的MD5
        :param file_name: 文件名
        :param block_size: 计算MD5的数据块大小，默认64KB
        :return 文件内容的MD5值
        """
        with open(file_name, 'rb') as f:
            md5 = hashlib.md5()
            while True:
                data = f.read(block_size)
                if not data:
                    break
                md5.update(data)
        return base64.b64encode(md5.digest())

    def calculate_data_md5(data):
        """计算数据的MD5
        :param data: 数据
        :return MD5值
        """
        md5 = hashlib.md5()
        md5.update(data)
        return base64.b64encode(md5.digest())

这个是sdk里面的MD5校验本地文件的sdk函数，
分片上传`bucket.upload_part(key, upload_id, part_number, data, headers={'Content-MD5': encodeMD5})`分片上传时用`calculate_data_md5（）`计算的分片md5是没问题的，当执行完分片上传后，合并分片时用
`encodeMD5 = calculate_file_md5(filename, block_size=blockSize)  `  计算好本地文件的MD5值
`bucket.complete_multipart_upload(key, upload_id, parts, headers={'Content-MD5': encodeMD5})`
当执行到这里的时候总是会返回错误InvalidDigest， 400 

如果是我的代码出的问题，希望给出个complete_multipart_upload， MD5校验的example，谢谢

**Comment by Linyee** [comment]
@yami

**Comment by yami** [comment]
@Linyee 注意到Content-Md5是校验HTTP Body的MD5。

complete_multipart_upload()本质上是发送一个 [CompleteMultipartUpload](https://help.aliyun.com/document_detail/31995.html) HTTP请求给OSS服务。这个请求的Body是描述所有要上传Part的一个XML。

此时你传入Content-Md5的意图校验文件的Md5，但是OSS服务认为这个Content-Md5是和这个XML进行校验。所以结果自然是不匹配的。

你可以计算文件的crc64，然后用crc64来校验文件的完整性。
